# Import Library

In [1]:
#open google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
import os
import pandas as pd
import scipy.io as sio
from PIL import Image
import numpy as np
import datetime

# Perhitungan Porositas Sebagai Label

## Porositas data training

In [28]:
path = "train_mat"
data = os.listdir(path)
# data = os.listdir(path)[0]
poro = []
for i in data:
    dmat = sio.loadmat(os.path.join(path,i))
#     dmat = sio.loadmat(os.path.join(path,data))
    dmat_co = list(dmat.items())
    arr_m = dmat_co[3][1] # ini maksudnya adalah mengambil data sebenarnya pada index ketiga lalu mengambil lagi di index pertama
    flat = arr_m.ravel() # menjadikan data menjadi satu dimensi
    total = len(flat)
    matriks = np.sum(flat)
    pori = total - matriks
    porositas = pori/total # melakukan perhitungan porositas
    poro.append(porositas)
# pokonya code ini berfungsi untuk melakukan pengambilan data pada awalnya dan melakukan manipulasi data untuk menghitung porositasnya
print("===============================")
porosity = {'filename' : data,
           'porosity' : poro}

df_por = pd.DataFrame(porosity)
df_por['filename'] = df_por['filename'].replace('.mat','.png', regex=True)
df_por.to_csv('train-porosity.csv', index=False)
print("selesai")

selesai


## Porositas data testing

In [29]:
path = r"test_mat"
data = os.listdir(path)
begin_time = datetime.datetime.now()
poro = []
for i in data:
    dmat = sio.loadmat(os.path.join(path,i))
    dmat_co = list(dmat.items())
    arr_m = dmat_co[3][1]
    flat = arr_m.ravel()
    total = len(flat)
    matriks = np.sum(flat)
    pori = total - matriks
    porositas = pori/total
    poro.append(porositas)

print("===============================")
print(datetime.datetime.now() - begin_time)
porosity = {'filename' : data,
           'porosity' : poro}

df_por = pd.DataFrame(porosity)
df_por['filename'] = df_por['filename'].replace('.mat','.png', regex=True)
df_por.to_csv('test-porosity.csv', index=False)
print("selesai")

0:00:02.261944
selesai


# Membuat RGB Sintetik sebagai Input

## RGB sintetik untuk data training

In [40]:
path = "train_mat"
sampel = os.listdir(path)
sampel = os.listdir(path)[0]
#print(type(sampel[0]))
rgb =  np.zeros([128,128,3], dtype = np.uint8)
ekstensi = '.png'
dest_folder = "RGB-sintetik"
print('===make rgb====')
# for i in sampel:
# dmat = sio.loadmat(os.path.join(path,i))
dmat = sio.loadmat(os.path.join(path,sampel))
dmat_conv = list(dmat.items())
arr = dmat_conv[3][1]
print(arr.shape)
arxy = arr[:,:,64]
(print(data_arxy) for data_arxy in arxy)
print('\narxy',100*'=')
aryz = arr[64,:,:]
print(aryz,'\naryz',100*'=')
arzx = arr[:,64,:]
print(arzx,'\narzx',100*'=')

#     xy = arxy * 255
#     yz = aryz * 255
#     zx = arzx * 255
#     rgb[:,:,0] = xy
#     rgb[:,:,1] = yz
#     rgb[:,:,2] = zx
#     img = Image.fromarray(rgb)
#     filename = i[:-4]+ ekstensi

#     img.save(os.path.join(dest_folder,filename))
# print('selesai')

===make rgb====
(128, 128, 128)

arxy ====================================================================================================
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]] 
aryz ====================================================================================================
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 0 0 0]] 
arzx ====================================================================================================


In [32]:
# Jadi ini adalah code untuk menghasilkan data rgb sintetik yang diambil dari data sesimik pada kedalam 64 (middle deep)
path = "train_mat"
sampel = os.listdir(path)
#print(type(sampel[0]))
rgb =  np.zeros([128,128,3], dtype = np.uint8) # kegunaan dari code ini adalah membuat suatu matriks 0 yang berukuran x=128,y=128, dan z=3
ekstensi = '.png'
dest_folder = "RGB-sintetik"
print('===make rgb====')
for i in sampel:
    dmat = sio.loadmat(os.path.join(path,i))
    dmat_conv = list(dmat.items())
    arr = dmat_conv[3][1]
    arxy = arr[:,:,64] # pada code ini dilakukan pengambilan dengan acuan z=64, jadi pada z = 64 data x dan y diambil keseluruhan hingga batas z=64
    aryz = arr[64,:,:] # sama halnya dengan ini
    arzx = arr[:,64,:] # dan ini
    xy = arxy * 255 # dilakukan normalisasi data yang sebelumnya datanya dari 0-1, dikali dengan 255 menjadi 0-255, yang sebelumnya grayscale menjadi rgb
    yz = aryz * 255
    zx = arzx * 255
    rgb[:,:,0] = xy # disimpan dalam format data merah
    rgb[:,:,1] = yz # disimpan dalam format data hijau
    rgb[:,:,2] = zx # disimpan dalam format data biru
    img = Image.fromarray(rgb)
    filename = i[:-4]+ ekstensi

    img.save(os.path.join(dest_folder,filename))
print('selesai')

===make rgb====
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


## RGB sintetik untuk data testing

In [6]:
#path = r"D:\2_Magister\wokshop HAGI\cnn\test_mat"
path = r"/content/drive/My Drive/pcworkshop/test_mat"
sampel = os.listdir(path)
#print(type(sampel[0]))
rgb =  np.zeros([128,128,3], dtype = np.uint8)
ekstensi = '.png'
dest_folder = r"/content/drive/My Drive/pcworkshop/RGB-sintetik"
print('===make rgb====')
for i in sampel:
    dmat = sio.loadmat(os.path.join(path,i))

    dmat_conv = list(dmat.items())
    arr = dmat_conv[3][1]
    arxy = arr[:,:,64]
    aryz = arr[64,:,:]
    arzx = arr[:,64,:]
    xy = arxy * 255
    yz = aryz * 255
    zx = arzx * 255
    rgb[:,:,0] = xy
    rgb[:,:,1] = yz
    rgb[:,:,2] = zx
    img = Image.fromarray(rgb)
    filename = i[:-4]+ ekstensi

    img.save(os.path.join(dest_folder,filename))
print('selesai')

===make rgb====
selesai


# Membuat Model CNN

In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
import datetime
import tensorflow as tf
from tensorflow import keras
import PIL

## Load dataset

In [2]:
path_input = "RGB-sintetik"
# load data train
data = pd.read_csv(r"train-porosity.csv")

#=================================================
full = []
for i in data['filename']:
    namepath = os.path.join(path_input,str(i))

    full.append(namepath)

df_n = data['porosity'].tolist()
dataset = {'filename' : full,
          'nilai' : df_n}
dataset = pd.DataFrame(dataset)
#==========================================

In [3]:
dataset.loc[0]

filename    RGB-sintetik\bb_1_129_1.png
nilai                          0.156565
Name: 0, dtype: object

In [4]:
#==========================================
train_generator = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)
train_images = train_generator.flow_from_dataframe(
    dataframe=dataset,
    x_col='filename',
    y_col='nilai',
    target_size=(128, 128),
    color_mode='rgb',
    class_mode='raw', # jadi kegunaan dari raw ini adalah untuk set target data sesuai dengan data yg diinput
    batch_size=32,
    shuffle=True,
    seed=42,
    subset='training'
)

Found 240 validated image filenames.


In [5]:
val_images = train_generator.flow_from_dataframe(
    dataframe=dataset,
    x_col='filename',
    y_col='nilai',
    target_size=(128, 128),
    color_mode='rgb',
    class_mode='raw', 
    batch_size=32,
    shuffle=True,
    seed=42,
    subset='validation'
)

Found 60 validated image filenames.


## Load Pre-trained model

In [11]:
dat = keras.Sequential()
base_model = keras.applications.MobileNetV2(
    weights="imagenet",  # Load weights pre-trained on ImageNet.
    input_shape=(128, 128, 3),
    include_top=False,
)


9406464/9406464 [==============================] - 0s 0us/step


## Freeze Model

In [12]:
base_model.trainable = False

## Fine Tuning

In [13]:
inputs = keras.Input(shape=(128, 128, 3))
x = dat(inputs)  # Apply random data augmentation
x = base_model(x, training=False) # code ini berfungsi untuk mengabaikan model dasar yang mana model dasar ini adalah model pretrained sehingga mempersingkat waktu pelatihan, dimana model pretrained hanya diimport bobotnya saja jadi tidak perlu untuk dilatih
x = keras.layers.GlobalMaxPool2D()(x)
x = keras.layers.Dropout(0.2)(x)  # Regularize with dropout
outputs = keras.layers.Dense(1)(x)
model = keras.Model(inputs, outputs)

# Compile Model

In [19]:
begin_time = datetime.datetime.now()
model.compile(
    optimizer='adam',
    loss='mse'
)

history = model.fit(
    train_images,
    validation_data=val_images,
    epochs=100, batch_size = 256)
print(datetime.datetime.now() - begin_time)
modsave = r'model'
model.save(os.path.join(modsave,'prediksi-porositas.h5'))

df = pd.DataFrame(history.history, columns= history.history.keys())
csv_save = r"/content/drive/My Drive/pcworkshop/history"
df.to_csv(os.path.join(csv_save,'prediksi-porositas.csv'), index = False, header=True)

print("SELESAI")

Epoch 1/100
8/8 [==============================] - 11s 733ms/step - loss: 0.8892 - val_loss: 0.6103
Epoch 2/100
8/8 [==============================] - 5s 715ms/step - loss: 0.8140 - val_loss: 0.5163
Epoch 3/100
8/8 [==============================] - 5s 535ms/step - loss: 0.9501 - val_loss: 0.4634
Epoch 4/100
8/8 [==============================] - 4s 571ms/step - loss: 0.8643 - val_loss: 0.6890
Epoch 5/100
8/8 [==============================] - 7s 856ms/step - loss: 0.7023 - val_loss: 0.6096
Epoch 6/100
8/8 [==============================] - 5s 577ms/step - loss: 0.6833 - val_loss: 0.4465
Epoch 7/100
8/8 [==============================] - 5s 573ms/step - loss: 0.6422 - val_loss: 0.4157
Epoch 8/100
8/8 [==============================] - 6s 793ms/step - loss: 0.7704 - val_loss: 0.3910
Epoch 9/100
8/8 [==============================] - 5s 599ms/step - loss: 0.6185 - val_loss: 0.3505
Epoch 10/100
8/8 [==============================] - 6s 802ms/step - loss: 0.7245 - val_loss: 0.3616
Epoch 11

# Prediksi

In [20]:
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
import tensorflow as tf
import datetime
from PIL import Image
import os
from sklearn.metrics import r2_score

## Load data testing

In [21]:
path_mo = r"model"
fdr = os.listdir(path_mo)
#modell = 'code7.h5'
modell = fdr[0]
#print('test_set0-rand')
print('>>> '+modell+' <<<<')
model_name = os.path.join(path_mo,modell)

model = load_model(model_name, compile=False)

# Import dataset pengujian
path_input = r"/content/drive/My Drive/pcworkshop/RGB-sintetik"
data = pd.read_csv(r"test-porosity.csv")

>>> prediksi-porositas.h5 <<<<


In [22]:
full = []
for i in data['filename']:
    namepath = os.path.join(path_input,str(i))
    full.append(namepath)

df_n = data['porosity'].tolist()
dataset = {'filename' : full,
          'porosity' : df_n}
dataset = pd.DataFrame(dataset)
d_train = []
for i in range(len(dataset)):
    data_i = dataset['filename'][i]
    img = Image.open(data_i)
    arr = np.array(img)
    #ars = np.reshape(arr,[1,128,128,3])
    sampel = arr/255
    d_train.append(sampel.tolist())

masukan = np.array(d_train)

label_train = []
for i in range(len(dataset)):
    label_i = dataset['porosity'][i]
    label_train.append(label_i)

target = np.array(label_train)

## Testing

In [23]:
#========= UJI =====================
begin_time = datetime.datetime.now()
pred = np.squeeze(model.predict(masukan))
print(datetime.datetime.now() - begin_time)

predictive_value = pred.flatten()
file_name = data['filename'].tolist()
true_value = data['porosity'].tolist()

pred_vs_true = {'filename' : file_name,
               'pred' : predictive_value,
               'true' : true_value}
pred_true = pd.DataFrame(pred_vs_true)

pred_true.to_csv('hasil-prediksi.csv', index=False)
yy = pred_true['pred']
xx = pred_true['true']
mape = tf.keras.losses.MeanAbsolutePercentageError()
mae = tf.keras.losses.MeanAbsoluteError()
loss_mape = mape(xx, yy).numpy()
loss_mae = mae(xx, yy).numpy()
loss_r2 = r2_score(xx, yy)
print('MAPE:', loss_mape)
print('MAE:', loss_mae)
print('R2:', loss_r2)
print('=====================================')

10/10 [==============================] - 4s 351ms/step
0:00:06.129230
MAPE: 24.11538
MAE: 0.05878046
R2: -2.3822250982348514
